### ISSUE TITLE
Unable to start razerdaemon.service 

### ISSUE THREAD

**Issue by HakonHarnes** [phush0/razer-laptop-control-no-dkms#11]
Specs: Razer Blade 15 2020

**Daemon status log**
× razerdaemon.service - Razer laptop control daemon
     Loaded: loaded (/usr/lib/systemd/user/razerdaemon.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Mon 2022-10-03 19:51:37 CEST; 58s ago
   Duration: 5ms
   Main PID: 9162 (code=exited, status=1/FAILURE)
        CPU: 5ms

Oct 03 19:51:37 manjaro systemd[1269]: Started Razer laptop control daemon.
Oct 03 19:51:37 manjaro daemon[9162]: suported devices found: 26
Oct 03 19:51:37 manjaro daemon[9162]: Error: hidapi error: Permission denied
Oct 03 19:51:37 manjaro daemon[9162]: no supported device found
Oct 03 19:51:37 manjaro systemd[1269]: razerdaemon.service: Main process exited, code=exited, status>
Oct 03 19:51:37 manjaro systemd[1269]: razerdaemon.service: Failed with result 'exit-code'.

**Describe the bug**
Running the install.sh script gives: 

Finished release [optimized] target(s) in 0.03s
Failed to stop razerdaemon.service: Unit razerdaemon.service not loaded.
Install complete!

**To Reproduce**

1. Run install.sh 
2. Try to start razerdaemon.service 

**Expected behavior**
Should be able to install and run razer-cli, but razerdaemon.service is not working.

**Comment by phush0** [comment]
You have not stated what distro you are using. Also what version of Blade you are using (advanced, base). Make sure it is listed in laptops.json file and ID match. Report back.

**Comment by HakonHarnes** [comment]
Manjaro Linux with kernel 5.16.65-1. Base model. 
I resolved the issue by restarting the computer.
