### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by b3nis** [phush0/razer-laptop-control-no-dkms#19]
**Describe the bug**
When setting custom power mode - level 3 on cpu results in level 2.
```
razer-cli write power ac 4 3 2
Write power: Args: ["4", "3", "2"]
RES: SetPowerMode { result: true }
RES: GetPwrLevel { pwr: 4 }
Current power setting: Custom
RES: GetCPUBoost { cpu: 2 }
Current CPU setting: High
RES: GetGPUBoost { gpu: 2 }
Current GPU setting: High
```

**Expected behavior**
Get level 3 on cpu.

This might be something to do with my Razer Blade - might not support higher than level 2 for cpu power? Running a Blade Base 2020 (i7-10750h). 

EDIT: I also want to add that thank you for doing this! Gonna figure out how to sponsor the project.

**Comment by phush0** [comment]
Boost mode (3) is not available for your model. If you want to test it edit json with models and add feature boost inside to your model. At the moment of writing this software only advanced models and studio supported this feature. Just add boost to your model and reboot.

**Comment by b3nis** [comment]
Thanks mate!

I just donated a small sum for your great work.

Take care!
