### ISSUE TITLE
[BUG] RGB keyboard not working after reboot

### ISSUE THREAD

**Issue by lexizz** [phush0/razer-laptop-control-no-dkms#22]
**Daemon status log**
`systemctl --user status razerdaemon.service`
![image](https://user-images.githubusercontent.com/22645458/226434348-7a99b055-8e2c-4577-97d1-48d0c2225944.png)
after enter the command: `razer-cli write effect static_gradient 0 255 0 13 214 255`
![image](https://user-images.githubusercontent.com/22645458/226434905-96e4901f-2134-4327-83b1-ccc782bcd631.png)

**Describe the bug**
After reboot RGB keyboard doesn't work. A button for manage rgb doesn't work too.

**To Reproduce**
enter the command, for example: `razer-cli write effect static_gradient 0 255 0 13 214 255` and reboot a laptop.

**Expected behavior**
After system reboot rgb of keyboard is working

**Optional but useful, packet capture from synapse**
I don't use synapse

**System**
Operating System: Manjaro Linux
KDE Plasma Version: 5.26.5
KDE Frameworks Version: 5.103.0
Qt Version: 5.15.8
Kernel Version: 6.2.7-2-MANJARO (64-bit)
Graphics Platform: X11
Processors: 8 × 11th Gen Intel® Core™ i7-1165G7 @ 2.80GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics
Manufacturer: Razer
Product Name: Blade Stealth 13 (Late 2020) - RZ09-0327
System Version: 0.04

**Additional question**
How can I remove your package complete? (It's for future)

**Comment by lexizz** [comment]
@dleviminzi Hi. Thank you so much

**Comment by dleviminzi** [comment]
> @dleviminzi Hi. Thank you so much

No problem. It is merged now, so using the latest you should be good.
