### ISSUE TITLE
Minimum fan speed less than 3500 rpm not possible

### ISSUE THREAD

**Issue by nima-1102** [phush0/razer-laptop-control-no-dkms#27]
**Daemon status log**
Jul 08 17:55:20 razer daemon[9866]: Command not supported
Jul 08 17:55:20 razer daemon[9866]: Command not supported
Jul 08 17:55:20 razer daemon[9866]: Command not supported
Jul 08 17:55:20 razer daemon[9866]: Command not supported
Jul 08 17:55:20 razer daemon[9866]: Command not supported
Jul 08 17:55:20 razer daemon[9866]: Command not supported
Jul 08 17:55:20 razer daemon[9866]: Command not supported
Jul 08 17:55:20 razer daemon[9866]: Command not supported
Jul 08 17:55:20 razer daemon[9866]: Command not supported
Jul 08 17:55:20 razer daemon[9866]: Command not supported

**Describe the bug**
The fan speed on my Razer Blade Stealth (Early 2020) cannot be set below 3500rpm. All values below 3500 become Fix 3500 rpm.
In the original Razer software in Windows the minimum is 2500rpm which I tested so it should be possible.

**To Reproduce**
$ razer-cli write fan ac 2500

RES: SetFanSpeed { result: true }
RES: GetFanSpeed { rpm: 3500 }
Current fan setting: 3500 RPM

**Expected behavior**
The rpm speed should be set to 2500rpm instead of 3500rpm.

**Comment by phush0** [comment]
Can not implement something that hardware is not supporting. There is lower limit for all models like it or not.

**Comment by nima-1102** [comment]
This is not correct, the hardware supports it, the official software provided by Razer, Synapse 3 gives me the possibility of 2500-5500rpm, see here: [Minimum](https://i.imgur.com/AVInEeE.png) - [Maximum](https://i.imgur.com/YWPaEYC.png)

You can clearly hear the difference, I think Razer will know what their hardware can do.
