### ISSUE TITLE
[BUG] Error. Socket doesn't exit. Is daemon running? [NEED  INFO]

### ISSUE THREAD

**Issue by benterova** [phush0/razer-laptop-control-no-dkms#3]
**Describe the bug**
After running `install.sh` as a normal user, the script succeeds but the daemon never gets enabled. 
There are no errors during the install script process, only a warning about an unused variable.

**To Reproduce**
- Clone the project
- Run `install.sh` from the `razer_control_gui` dir
- Attempt to run `razer-cli` from the console.

**Expected behavior**
Have a started `razerdaemon.service` to attach execute `razer-cli` against.

**Additional info** 
Running Arch on 5.18.2-zen1-1-zen, Blade 15 Advanced Model (Early 2020) - RZ09-033 5.04.

Also, I have transitioned to this project from `razer-control-dkms` installed & uninstalled via the AUR, so there may be some sort of conflict there.

Let me know what other info may be useful to help troubleshoot.

**Comment by benterova** [comment]
Script Output:

```
benterova@laptop-party ~/D/r/razer_control_gui> ./install.sh
warning: field is never read: `brightness`
   --> src/kbd/board.rs:188:5
    |
188 |     brightness: u8,
    |     ^^^^^^^^^^^^^^
    |
    = note: `#[warn(dead_code)]` on by default
note: `KeyboardData` has derived impls for the traits `Debug` and `Clone`, but these are intentionally ignored during dead code analysis
   --> src/kbd/board.rs:185:16
    |
185 | #[derive(Copy, Clone, Debug)]
    |                ^^^^^  ^^^^^
    = note: this warning originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)

warning: `service` (bin "daemon") generated 1 warning
    Finished release [optimized] target(s) in 0.04s
[sudo] password for benterova: 
Failed to stop razerdaemon.service: Unit razerdaemon.service not loaded.
Install complete!
```

**Comment by phush0** [comment]
Closing as info is not provided

**Comment by benterova** [comment]
Sorry for not providing info in a timely manner, however I was able to solve this and I thought it may be useful for someone in the future:

After running `systemctl --user status razerdaemon.service`, I was able to see a `hidapi: permission denied` error. I looked into the udev rules and saw that the device permissions require your user to be part of the `plugdev` group. After creating this group and adding my user to it, everything was smooth from there.

May be a good idea to add the checking & creation of user's `plugdev` group status to the installation script.

**Comment by smutao** [comment]
> Sorry for not providing info in a timely manner, however I was able to solve this and I thought it may be useful for someone in the future:
> 
> After running `systemctl --user status razerdaemon.service`, I was able to see a `hidapi: permission denied` error. I looked into the udev rules and saw that the device permissions require your user to be part of the `plugdev` group. After creating this group and adding my user to it, everything was smooth from there.
> 
> May be a good idea to add the checking & creation of user's `plugdev` group status to the installation script.

sudo  usermod -a -G  plugdev $USER
then reboot

**Comment by l3ifk** [comment]
I also get the error when trying to use razer-cli and the ouput of `systemctl --user status razerdaemon.service
` is `× razerdaemon.service - Razer laptop control daemon
     Loaded: loaded (/usr/lib/systemd/user/razerdaemon.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-12-26 20:46:48 CET; 15s ago
   Duration: 5ms
    Process: 97630 ExecStart=/usr/share/razercontrol/daemon (code=exited, status=1/FAILURE)
   Main PID: 97630 (code=exited, status=1/FAILURE)
        CPU: 5ms

Dec 26 20:46:48 blade14 systemd[2305]: Started razerdaemon.service - Razer laptop control >
Dec 26 20:46:48 blade14 daemon[97630]: suported devices found: 33
Dec 26 20:46:48 blade14 daemon[97630]: Error: hidapi error: failed to open device with pat>
Dec 26 20:46:48 blade14 daemon[97630]: no supported device found
Dec 26 20:46:48 blade14 systemd[2305]: razerdaemon.service: Main process exited, code=exit>
Dec 26 20:46:48 blade14 systemd[2305]: razerdaemon.service: Failed with result 'exit-code'.`

**Comment by l3ifk** [comment]
I also get the same error when trying to use razer-cli... The output of `systemctl --user status razerdaemon.service` is : 

× razerdaemon.service - Razer laptop control daemon
     Loaded: loaded (/usr/lib/systemd/user/razerdaemon.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Tue 2023-12-26 20:46:48 CET; 9min ago
   Duration: 5ms
    Process: 97630 ExecStart=/usr/share/razercontrol/daemon (code=exited, status=1/FAILURE)
   Main PID: 97630 (code=exited, status=1/FAILURE)
        CPU: 5ms

Dec 26 20:46:48 blade14 systemd[2305]: Started razerdaemon.service - Razer laptop control daemon.
Dec 26 20:46:48 blade14 daemon[97630]: suported devices found: 33
Dec 26 20:46:48 blade14 daemon[97630]: Error: hidapi error: failed to open device with path /dev/hidraw0: Permission denied (os error 13)
Dec 26 20:46:48 blade14 daemon[97630]: no supported device found
Dec 26 20:46:48 blade14 systemd[2305]: razerdaemon.service: Main process exited, code=exited, status=1/FAILURE
Dec 26 20:46:48 blade14 systemd[2305]: razerdaemon.service: Failed with result 'exit-code'.
